name: Tests

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Unit Tests [PHP ${{ matrix.php-versions }}]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer update --no-progress --prefer-dist --prefer-stable --optimize-autoloader --quiet
          composer update --no-progress --prefer-dist --prefer-stable --optimize-autoloader --quiet --working-dir=vendor-bin/contributte

      - name: Run tests
        run: vendor/bin/tester -C -s ./tests

      - name: Install dependencies (lowest)
        run: |
          composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable --optimize-autoloader --quiet
          composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable --optimize-autoloader --quiet --working-dir=vendor-bin/contributte

      - name: Install Contributte dependencies
        uses: ramsey/composer-install@v2
        with:
          working-directory: vendor-bin/contributte

      - name: Run tests
        run: vendor/bin/tester -C -s ./tests
